# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3

      - name: Install Tuist
        uses: jdx/mise-action@v2

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app
      - name: Check Xcode version
        run: xcodebuild -version

      - name: Build unsigned .xcarchive
        run: |
          set -o pipefail
          xcodebuild clean archive \
            -project BundlerSizer.xcodeproj \
            -scheme BundlerSizer \
            -sdk iphonesimulator \
            -configuration Release \
            -archivePath $PWD/build/BundlerSizer.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          | xcpretty

      - name: Inspect bundle with Tuist
        run: |
          tuist inspect bundle build/BundlerSizer.xcarchive
